apiVersion: v2
name: sonarr
version: "0.1.26"
description: sonarr is a lightweight, Free Software, cross-platform BitTorrent client.
icon: https://docs.linuxserver.io/assets/icon.svg
type: application
sources:
  - https://docs.linuxserver.io/images/docker-sonarr
  - https://github.com/linuxserver/docker-sonarr
# renovate: image=lscr.io/linuxserver/sonarr
appVersion: "4.0.12"
