apiVersion: v2
description: Jellyfin Media Server
name: jellyfin
version: "0.1.20"
type: application
sources:
  - docker.io/jellyfin/jellyfin
# renovate: image=docker.io/jellyfin/jellyfin
appVersion: "10.9.6"
