apiVersion: v2
name: calibre
description: calibre is an organizer and contentserver for books.
icon: https://docs.linuxserver.io/assets/icon.svg
version: "0.1.28"
type: application
sources:
  - https://docs.linuxserver.io/images/docker-calibre
# renovate: image=lscr.io/linuxserver/calibre
appVersion: "7.14.0"
