apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webuiPort }}
      targetPort: http
      protocol: TCP
      name: http
    - name: "{{ .Values.service.torrentingPort }}"
      port: {{ .Values.service.torrentingPort }}
      protocol: TCP
      targetPort: {{ .Values.service.torrentingPort }}
    - name: "{{ .Values.service.torrentingPort }}-udp"
      port: {{ .Values.service.torrentingPort }}
      protocol: UDP
      targetPort: {{ .Values.service.torrentingPort }}
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
