apiVersion: v1
kind: Service
metadata:
  name: {{ include "deluge.fullname" . }}
  labels:
    {{- include "deluge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: "{{ .Values.service.uploadPort }}"
      port: {{ .Values.service.uploadPort }}
      protocol: TCP
      targetPort: {{ .Values.service.uploadPort }}
    - name: "{{ .Values.service.uploadPort }}-udp"
      port: {{ .Values.service.uploadPort }}
      protocol: UDP
      targetPort: {{ .Values.service.uploadPort }}
    - name: "{{ .Values.service.rpcPort }}"
      port: {{ .Values.service.rpcPort }}
      protocol: TCP
      targetPort: {{ .Values.service.rpcPort }}
  selector:
    {{- include "deluge.selectorLabels" . | nindent 4 }}
