{{- if .Values.servicemonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "speedtest-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.servicemonitor.interval }}
    {{- if .Values.servicemonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.servicemonitor.scrapeTimeout }}
    {{- end }}
{{- end }}
