apiVersion: v2
name: vikunja
version: 0.2.1
description: "The Todo-app to organize your life."
icon: https://kolaente.dev/vikunja/vikunja/raw/branch/main/frontend/public/images/icons/icon-maskable.png
type: application
sources:
  - https://kolaente.dev/vikunja/vikunja
# renovate: image=docker.io/vikunja/vikunja
appVersion: "0.24.6"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.0
  - name: postgresql
    version: 14.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 16.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
    condition: redis.enabled
