controllers:
  main:
    containers:
      main:
        image:
          repository: gotson/komga
          tag: ""
        env:
          TZ: "UTC"

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 25600


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      # nginx.ingress.kubernetes.io/proxy-body-size: 64m
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: komga.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: komga.local
        hosts:
          - komga.local

persistence:
  config:
    enabled: false
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /config
    hostPath: /path/to/your/config/komga
