{{- include "bjw-s.common.loader.init" . }}

{{- define "paperless-ngx.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}
# Container to use
controllers:
  main:
    enabled: true
    type: deployment
    containers:
      main:
        image:
          repository: ghcr.io/paperless-ngx/paperless-ngx
          {{ if not .Values.image.tag -}}
          tag: "{{ .Chart.AppVersion }}"
          {{- end }}
{{- end -}}

{{- define "paperless-ngx.Values" -}}
controllers:
  main:
    containers:
      main:
        env:
          PAPERLESS_TIME_ZONE: {{ .Values.env.TZ }}
          PAPERLESS_PORT: {{ quote .Values.service.main.ports.http.port }}
          {{- if .Values.config -}}
          {{ .Values.config | toYaml }}
          {{- end }}
          {{- with .Values.ingress.main }}{{- if and .enabled .hosts }}
          PAPERLESS_URL: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}
          {{- end }}{{- end }}

          {{- if .Values.postgresql.enabled }}
          {{- with .Values.postgresql }}
          PAPERLESS_DBENGINE: postgresql
          PAPERLESS_DBHOST: {{ $.Release.Name }}-postgresql
          PAPERLESS_DBNAME: {{ .auth.database }}
          PAPERLESS_DBUSER: {{ default "postgres" .auth.username }}
          PAPERLESS_DBPASS:
            secretKeyRef:
              name: {{ $.Release.Name }}-postgresql
              key: {{ if not .auth.password }}postgres-{{ end }}password
          {{- end }}
          {{- else if .Values.mariadb.enabled }}
          {{- with .Values.mariadb}}
          PAPERLESS_DBENGINE: mariadb
          PAPERLESS_DBHOST: {{ $.Release.Name }}-mariadb
          PAPERLESS_DBNAME: {{ .auth.database }}
          PAPERLESS_DBUSER: {{ .auth.username }}
          PAPERLESS_DBPASS:
            secretKeyRef:
              name: {{ $.Release.Name }}-mariadb
              key: mariadb-password
          {{- end }}
          {{- end }}

          {{- if .Values.redis.enabled }}
          {{- with .Values.redis }}
          A_REDIS_PASSWORD:
            secretKeyRef:
              name: {{ $.Release.Name }}-redis
              key: redis-password
          PAPERLESS_REDIS: redis://{{ .auth.username }}:$(A_REDIS_PASSWORD)@{{ $.Release.Name }}-redis-master
          {{- end }}
          {{- end }}
{{- end -}}

{{- $_ := mergeOverwrite .Values (include "paperless-ngx.hardcodedValues" . | fromYaml) -}}
{{- $_ := mergeOverwrite .Values (include "paperless-ngx.Values" . | fromYaml) -}}


{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
