apiVersion: v2
name: cwadownloader
version: 0.2.2
description: "Search for books on Anna's Archive"
type: application
sources:
  - https://github.com/calibrain/calibre-web-automated-book-downloader
# renovate: image=ghcr.io/calibrain/calibre-web-automated-book-downloader
appVersion: "20250125"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.0
