controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/cwadownloader-api
          tag: latest
        env:
          FLASK_PORT: 8084
          FLASK_DEBUG: false
          CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
          INGEST_DIR: /cwa-book-ingest
          BOOK_LANGUAGE: en
          TZ: "Etc/UTC"
          PUID: "1000"
          PGID: "1000"
      cloudflarebypassforscraping:
        image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 8084
  cloudflarebypassforscraping:
    controller: main
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      # nginx.ingress.kubernetes.io/proxy-body-size: 64m
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: cwadownloader.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: cwadownloader.local
        hosts:
          - cwadownloader.local

persistence:
  ingest:
    enabled: false
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /cwa-book-ingest
    hostPath: /path/to/your/ingest/folder
