controllers:
  main:
    containers:
      main:
        image:
          repository: riffsphereha/newznabarr
          tag: ""
        env:
          TZ: "UTC"

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 10000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      # nginx.ingress.kubernetes.io/proxy-body-size: 64m
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: chart-example.local
        hosts:
          - chart-example.local

persistence:
  newznabarr-config:
    enabled: true
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /app/config
    hostPath: /path/to/your/config/newznabarr
  newznabarr-data:
    enabled: true
    retain: true
    accessMode: ReadWriteOnce
    size: 500Gi
    advancedMounts:
      main:
        main:
          - path: /data/downloads/downloadarr
