controllers:
  main:
    containers:
      main:
        image:
          repository: riffsphereha/newznabarr
          tag: latest
        env:
          TZ: "UTC"

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 10000

persistence:
  newznabarr-config:
    enabled: true
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /app/config
    hostPath: /path/to/your/config/newznabarr
  newznabarr-data:
    enabled: true
    retain: true
    accessMode: ReadWriteOnce
    size: 500Gi
    advancedMounts:
      main:
        main:
          - path: /data/downloads/downloadarr
