{{- if .Values.ingress.internal.enabled -}}
{{- $fullName := include "mealie.fullname" . -}}
{{- $thisName := print $fullName "-internal" -}}
{{- $port := .Values.service.ports.api -}}
{{- if and .Values.ingress.internal.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.internal.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.internal.annotations "kubernetes.io/ingress.class" .Values.ingress.internal.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $thisName }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
  {{- with .Values.ingress.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.internal.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.internal.className }}
  {{- end }}
  {{- if .Values.ingress.internal.tls }}
  tls:
    {{- range .Values.ingress.internal.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.ingress.external.enabled -}}
{{- $fullName := include "mealie.fullname" . -}}
{{- $thisName := print $fullName "-external" -}}
{{- $port := .Values.service.ports.api -}}
{{- if and .Values.ingress.external.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.external.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.external.annotations "kubernetes.io/ingress.class" .Values.ingress.external.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $thisName }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
  {{- with .Values.ingress.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.external.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.external.className }}
  {{- end }}
  {{- if .Values.ingress.external.tls }}
  tls:
    {{- range .Values.ingress.external.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.external.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
