apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: https
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
