apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "searcharr.fullname" . }}
  labels:
    {{- include "searcharr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "searcharr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "searcharr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/data
              subPath: data
              name: {{ .Chart.Name }}
            - mountPath: /app/settings.py
              subPath: settings.py
              name: {{ .Chart.Name }}
            - mountPath: /app/logs
              subPath: logs
              name: {{ .Chart.Name }}
      volumes:
        - name: searcharr
          hostPath:
            path: "/var/nfs/kubernetes/mediastack/config/{{ include "searcharr.fullname" . }}"
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
