apiVersion: v2
name: apprise
version: 0.2.3
description: "apprise"
type: application
sources:
  - https://github.com/gotson/apprise
# renovate: image=lscr.io/linuxserver/apprise-api
appVersion: "1.1.8"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.1
