controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/apprise-api
          tag: ""
        env:
          TZ: "Etc/UTC"
          PUID: "1000"
          PGID: "1000"
          APPRISE_ATTACH_SIZE: "0" # Optional

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 8000


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      # nginx.ingress.kubernetes.io/proxy-body-size: 64m
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: apprise.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: apprise.local
        hosts:
          - apprise.local

persistence:
  config:
    enabled: false
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /config
    hostPath: /path/to/your/config/apprise
  # Optional Attachments
  attachments:
    enabled: false
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /attachments
    hostPath: /path/to/apprise/attachments
