controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/kieraneglin/pinchflat
          tag: latest
        env:
          # For a list of env vars, see https://github.com/kieraneglin/pinchflat
          TZ: "UTC"

serviceAccount:
  create: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    controller: main
    ports:
      http:
        port: 8945

persistence:
  pinchflat-config:
    enabled: false
    type: hostPath
    hostPathType: DirectoryOrCreate
    advancedMounts:
      main:
        main:
          - path: /config
    hostPath: /path/to/your/config/pinchflat
  pinchflat-data:
    enabled: false
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    size: 2000Gi
    advancedMounts:
      main:
        main:
          - path: /downloads

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # annotations:
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: pinchflat.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: pinchflat-tls
        hosts:
          - pinchflat.local
