apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storm.fullname" . }}
  labels:
    {{- include "storm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "storm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "storm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "storm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: DELUGE_RPC_HOSTNAME
              value: "{{ .Values.environment.DELUGE_RPC_HOSTNAME }}"
            - name: DELUGE_RPC_PORT
              value: "{{ .Values.environment.DELUGE_RPC_PORT }}"
            - name: DELUGE_RPC_USERNAME
              value: "{{ .Values.environment.DELUGE_RPC_USERNAME }}"
            - name: DELUGE_RPC_PASSWORD
              value: "{{ .Values.environment.DELUGE_RPC_PASSWORD }}"
            - name: DELUGE_RPC_VERSION
              value: "{{ .Values.environment.DELUGE_RPC_VERSION }}"
            - name: STORM_API_KEY
              value: "{{ .Values.environment.STORM_API_KEY }}"
            - name: STORM_BASE_PATH
              value: "{{ .Values.environment.STORM_BASE_PATH }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
