apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calibre.fullname" . }}
  labels:
    {{- include "calibre.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calibre.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calibre.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calibre.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: CUSTOM_USER
              value: "{{ .Values.username }}"
            - name: PASSWORD
              value: "{{ .Values.password }}"
            - name: CALIBRE_CONFIG_DIRECTORY
              value: "/config" # FIXME: Needs proper variables/values
            - name: CALIBRE_OVERRIDE_DATABASE_PATH
              value: "/config/metadata.db" # FIXME: Needs proper variables/values
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.vnc }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: calibre-config
            - mountPath: /media
              name: calibre-media
      volumes:
        - name: calibre-config
          hostPath:
            path: /var/nfs/kubernetes/mediastack/config/calibre
            type: DirectoryOrCreate
        - name: calibre-media
          persistentVolumeClaim:
            claimName: calibre-media
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
