apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre.fullname" . }}
  labels:
    {{- include "calibre.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.vnc }}
      targetPort: http
      protocol: TCP
      name: vnc
    - port: {{ .Values.service.ports.contentserver }}
      targetPort: 8081
      protocol: TCP
      name: contentserver
  selector:
    {{- include "calibre.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre.fullname" . }}-wireless-device
  labels:
    {{- include "calibre.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "lan"
    metallb.universe.tf/loadBalancerIPs: 192.168.2.200
    metallb.universe.tf/address-pool: lan
spec:
  type: LoadBalancer
  ports:
    - port: 9099
      targetPort: 9099
      protocol: TCP
  selector:
    {{- include "calibre.selectorLabels" . | nindent 4 }}
