apiVersion: v2
name: lazylibrarian
version: "0.1.1"
description: The Lazy Librarian is a for books.
icon: https://docs.linuxserver.io/assets/icon.svg
type: application
sources:
  - https://docs.linuxserver.io/images/docker-lazylibrarian
# renovate: image=lscr.io/linuxserver/lazylibrarian
appVersion:  "version-be7d9ccf"
