name: Bump versions and generate docs

on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  #   paths:
  #     - 'charts/**'
  push:
    branches:
      - renovate/**
    paths:
      - 'charts/**'

env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GTIHUB_REF_NAME: ${{ github.ref_name }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}

permissions:
  checks: write
  contents: write

jobs:

  debug:
    name: Useful info
    runs-on: ubuntu-latest

    steps:
      - name: Print useful info
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF_NAME: $GTIHUB_REF_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"

  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files-specific.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name}}

      - name: Check changed charts
        id: changed-files-specific
        uses: tj-actions/changed-files@v44
        with:
          files: |
            charts/**
          json: true

      - name: Set Matrix
        id: set-matrix
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-files-specific.outputs.all_changed_files }} | jq -c '. | map(split("/")[1]) | unique')
          echo $DATA
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"

  bump-versions:
    name: Update Charts
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.any_changed == 'true' && github.actor == 'renovate[bot]' }}
    needs: [changed-files]
    strategy:
      max-parallel: 1
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: ${{ github.head_ref || github.ref_name}}
      - run: |
          git pull origin ${{ github.head_ref || github.ref_name }}

      - name: Bump Chart Version
        env:
          CHART: ${{ matrix.charts }}
        run: |
          ./scripts/bumpversion-helmchart.sh

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1.2.11
        with:
          chart-search-root: "./charts/${{ matrix.charts }}"

      - name: Commit Changes and Push
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          CHART: ${{ matrix.charts }}
        with:
          commit_message: "chore: bump ${{ matrix.charts }} to ${{ env.VERSION }}"
          commit_author: Github Actions <actions@github.com>
          branch: ${{ github.head_ref || github.ref_name }}
          push_options: '--force'

  check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - changed-files
      - bump-versions
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    steps:
      - name: Pass
        run: echo "All checks passed"
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with:
    #       fetch-depth: 0
    #       token: "${{ secrets.WORKFLOW_TOKEN }}"
    #       ref: ${{ github.head_ref || github.ref_name }}
    #   - name: Commit to the PR branch to make status check pass
    #     run: |
    #       git config --global user.name "github-actions[bot]"
    #       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #       git commit --allow-empty -m "all checks passed for branch ${{ github.ref_name }} [skip ci]"
    #       git push origin ${{ github.head_ref || github.ref_name }}
