name: Bump versions and generate docs on demand

on:
  push:
    branches:
      - main

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    if: contains(github.event.head_commit.message, 'please bump:')
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Set Matrix
        id: set-matrix
        run: |
          set -eux
          DATA=$(echo ${{ github.event.head_commit.message }} | grep -o '\[.*\]')
          echo $DATA
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"

  bump-versions:
    name: Update Charts
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    needs: [changed-files]
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Bump Chart Version
        env:
          CHART: ${{ matrix.charts }}
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          ./scripts/bumpversion-helmchart.sh

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1.2.11

      - name: Commit Changes and Push
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          CHART: ${{ matrix.charts }}
        with:
          commit_message: "chore: bump ${{ matrix.charts }} to ${{ env.VERSION }}"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          branch: ${{ github.head_ref || github.ref_name }}

  check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - changed-files
      - bump-versions
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    steps:
      - name: Check
        run: |
          echo "Check complete!"
