name: Bump versions and generate docs

on:
  push:
    branches:
      - 'renovate/**'
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main


jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files-specific.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed charts
        id: changed-files-specific
        uses: tj-actions/changed-files@v44
        with:
          files: |
            charts/**
          json: true

      - name: Set Matrix
        id: set-matrix
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-files-specific.outputs.all_changed_files }} | jq -c '. | map(split("/")[1]) | unique')
          echo $DATA
          echo changed is ${{ steps.changed-files-specific.outputs.any_changed }}
          echo actor is ${{ github.actor }}
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"

  bump-versions:
    name: Update Charts
    runs-on: ubuntu-latest
    # if: ${{ needs.changed-files.outputs.any_changed == 'true' && github.actor == 'renovate[bot]' }}
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    needs: [changed-files]
    outputs:
      commit_hash: ${{ steps.commit-changes.outputs.commit_hash }}
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Chart Version
        env:
          CHART: ${{ matrix.charts }}
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          ./scripts/bumpversion-helmchart.sh

      - name: Commit Changes and Push
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          CHART: ${{ matrix.charts }}
        with:
          commit_message: "chore: bump ${{ matrix.charts }} to ${{ env.VERSION }}"
          commit_user_name: "Renovate Bot"
          commit_user_email: "bot@pepperlink.nl"

  docs-and-push:
    name: Generate helm docs and push back
    runs-on: ubuntu-latest
    needs: [bump-versions]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-versions.outputs.commit_hash }}
          fetch-depth: 0

      - name: Run helm-docs and push back
        uses: losisin/helm-docs-github-action@v1.2.11

      - name: Commit Changes and Push
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Helm documentation for ${{ github.ref_name }}"
          commit_user_name: "Renovate Bot"
          commit_user_email: "bot@pepperlink.nl"
          branch: ${{ github.head_ref || github.ref_name }}

  check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - changed-files
      - bump-versions
      - docs-and-push
    # if: ${{ success() }}
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    steps:
      - name: Check
        run: |
          echo "Check complete!"
