name: Release Charts

on:
  pull_request:
    types:
      - closed
  workflow_run:
    workflows:
      - "Bump versions and generate docs on demand"
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' ||  github.event.pull_request.merged == true

    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
